services:
  textdiff:
    image: textdiff:latest
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - /opt/textdiff/dist:/build/dist
    entrypoint: ["echo", "Build complete"]
